# Generated by Django 5.2.4 on 2026-01-15 08:29

import django.utils.timezone
import django_countries.fields
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "username",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        unique=True,
                        verbose_name="Username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="First Name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="Last Name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        max_length=254,
                        unique=True,
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        default="Other",
                        max_length=20,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        default="+234123456789",
                        max_length=30,
                        region=None,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "profile_photo",
                    models.ImageField(
                        default="/profile_default.png",
                        upload_to="",
                        verbose_name="Profile photo",
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        default="NG", max_length=2, verbose_name="Country"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        default="Abuja", max_length=180, verbose_name="City"
                    ),
                ),
                ("is_staff", models.BooleanField(db_index=True, default=False)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "date_joined",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("failed_login_attempts", models.IntegerField(default=0)),
                ("is_locked", models.BooleanField(db_index=True, default=False)),
                ("otp", models.CharField(blank=True, max_length=6, null=True)),
                ("otp_expiry", models.DateTimeField(blank=True, null=True)),
                ("max_otp_try", models.IntegerField(default=3)),
                ("otp_try_count", models.IntegerField(default=0)),
                ("is_verified", models.BooleanField(db_index=True, default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "indexes": [
                    models.Index(
                        fields=["email", "is_active"],
                        name="users_user_email_3f6199_idx",
                    ),
                    models.Index(
                        fields=["username", "is_active"],
                        name="users_user_usernam_6cca96_idx",
                    ),
                    models.Index(
                        fields=["is_staff", "is_active"],
                        name="users_user_is_staf_5f907d_idx",
                    ),
                    models.Index(
                        fields=["date_joined", "is_active"],
                        name="users_user_date_jo_dc0b93_idx",
                    ),
                    models.Index(
                        fields=["is_locked", "failed_login_attempts"],
                        name="users_user_is_lock_8f77a2_idx",
                    ),
                    models.Index(
                        fields=["first_name", "last_name"],
                        name="users_user_first_n_6d862e_idx",
                    ),
                    models.Index(
                        fields=["is_verified", "is_active"],
                        name="users_user_is_veri_6fe005_idx",
                    ),
                    models.Index(
                        fields=["otp_expiry"], name="users_user_otp_exp_ab77bf_idx"
                    ),
                ],
            },
        ),
    ]
